[".vim/pack/colors/opt/gruvbox-material"]
    type = "archive"
    url = "https://github.com/sainnhe/gruvbox-material/archive/11d779b26a9ab2b3db8c22c6ac9fb6e8ed4fea79.tar.gz"
    stripComponents = 1
    exact = true
    exclude = ["*/.git/**"]

[".vim/pack/dist/start/vim-airline"]
    type = "archive"
    url = "https://github.com/vim-airline/vim-airline/archive/9e0beefd6e28c92d876559f07d8595f454c08cb7.tar.gz"
    stripComponents = 1
    exact = true
    exclude = ["*/.git/**"]
