# ==========================
# ===  BEHAVIOR ========
# ==========================

# Change the default $TERM to tmux-256color
set -g default-terminal "tmux-256color"
set-option -g default-shell /bin/zsh

set -g mouse on

# No bells at all
set -g bell-action none

# Use vim keybindings in copy mode
setw -g mode-keys vi

# Fix ESC delay in vim
set -g escape-time 10

# ==========================
# ===  APPEARANCE  ========
# ==========================

# Some tweaks to the status line
set -g status-right "%H:%M"
set -g window-status-current-style "underscore"

display-message "tmux config loaded"
set -g message-style 'fg=yellow bg=red bold'

# clock mode
setw -g clock-mode-colour yellow

# copy mode
setw -g mode-style 'fg=black bg=red bold'

# panes
set -g pane-border-style 'fg=red'
set -g pane-active-border-style 'fg=yellow'

# ==========================
# ===  KEYBINDINGS  =======
# ==========================

# reload config file (change file location to your the tmux.conf you want to use)
bind r source-file ~/.tmux.conf

# Change the prefix key to C-a
set -g prefix C-a
unbind C-b
bind C-a send-prefix

