# ==========================
# === GENERAL BEHAVIOR =====
# ==========================

# --- Behavior ---
set -g default-terminal "tmux-256color"
set-option -g default-shell /bin/zsh
set -g mouse on
set -g bell-action none
set -g escape-time 10
set -g prefix C-a
unbind C-b

# --- Keymaps ---
bind r source-file ~/.tmux.conf
bind C-a send-prefix

# --- Appearance ---
set -g status-right "%H:%M"
set -g window-status-current-style "underscore"
display-message "tmux config loaded"
set -g message-style 'fg=yellow bg=red bold'
setw -g clock-mode-colour yellow

# ==========================
# === COPY MODE ============
# ==========================

# --- Behavior ---
setw -g mode-keys vi

# --- Keymaps ---
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle

# --- Appearance ---
set-window-option -g mode-style "fg=black,bg=yellow,bold"

# ==========================
# === NAVIGATION ===========
# ==========================

# --- Behavior ---

# --- Keymaps ---

# --- Appearance ---
set -g pane-border-style 'fg=red'
set -g pane-active-border-style 'fg=yellow'
